# Generated by Django 4.2.11 on 2024-06-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='Descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productos',
            name='Nombre',
            field=models.CharField(max_length=25),
        ),
    ]
