# Generated by Django 5.1.2 on 2024-11-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0002_alter_productos_descripcion_alter_productos_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='Imagen',
            field=models.ImageField(null=True, upload_to='Productos'),
        ),
    ]
